### ISSUE TITLE
Set up

### ISSUE THREAD

**Issue by kevinsoltis41** [squdgy/dailyfantasystatstool#3]
I saw you said in teh readme that you could use node, and I've just started with that, is there a step by step you could provide to get it up and running? -Thanks

**Comment by squdgy** [comment]
This app is a front end app that uses a back end API that is in a totally different project. That API is not open source. The app can work in any web server, even nodeJs. There is a server.js file included and all required node packages are checked into git.  To get it up and running should be as simple as installing node and then running server.js, and then navigating to index.html. You may have to change the port number in server.js. I run this through c9.io all the time, but it's been ages since I've tried to check out and run from scratch, so I may have forgotten something. This app is not terribly useful without the backend API(i.e. data), and I'm not sure if I've opened that up so that code from other apps can call it.
